#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Function:
    1. read displaced supercell files generated by Phonopy (POSCAR-001, POSCAR-002, etc.);
    2. calculate forces using machine learning potentials;
    3. write a FORCE_SETS file for Phonopy post-processing.

Author: Peng-Hu Du, penghdu@foxmail.com
Date: 2025.12.31
"""


import numpy as np
import os
import glob
import sys
import time
from phonopy.interface.vasp import read_vasp
from phonopy.file_IO import write_FORCE_SETS
from ase import Atoms


def create_ml_calculator(potential_type='nep', potential_file='nep.txt', **kwargs):
    """
    创建机器学习势函数计算器
    
    Parameters:
        potential_type (str): 势函数类型，可选'mace', 'dp', 'nep', 'flare', 'gap', 'lammps', 'emt'
        potential_file (str): 势函数文件
        **kwargs: 其他计算器参数
        
    Returns:
        ASE calculator: 机器学习势函数计算器实例
    """
    print(f"\nCreating {potential_type.upper()} calculator...")
        
    if potential_type == 'mace':
        try:
            from mace.calculators import MACECalculator
            device = kwargs.get('device', 'cpu')
            print(f"  - Loading MACE model from: {potential_file}, Device: {device}")
            return MACECalculator(model_paths=potential_file, device=device)
        except ImportError:
            print("  - MACE calculator not available. Install with: pip install mace-torch torch")
    elif potential_type == 'dp':
        try:
            from deepmd.calculator import DP
            print(f"  - Loading DP model from: {potential_file}")
            return DP(model=potential_file)
        except ImportError:
            print("  - DP calculator not available. Install with: pip install deepmd-kit ase")
    elif potential_type == 'nep':
        for import_path in ['pynep.calculate', 'ase.calculators.nep']:
            try:
                module = __import__(import_path, fromlist=['NEP'])
                print(f"  - Loading NEP potential from: {potential_file}")
                return module.NEP(potential_file)
            except ImportError:
                continue
        print("  - NEP calculator not available. Install with: pip install pynep")
    elif potential_type == 'flare':
        try:
            from flare.ase import FLARECalculator
            print(f"  - Loading FLARE model from: {potential_file}")
            return FLARECalculator(potential_file, **kwargs)
        except ImportError:
            print("  - FLARE calculator not available. Install with: pip install flare")
    elif potential_type == 'gap':
        try:
            from quippy.potential import Potential
            print(f"  - Loading GAP potential from: {potential_file}")
            return Potential(param_filename=potential_file, **kwargs)
        except ImportError:
            print("  - GAP calculator not available. Install with: pip install quippy-ase")
    elif potential_type == 'lammps':
        try:
            from ase.calculators.lammpsrun import LAMMPS
            print("  - Setting up LAMMPS calculator...")
            return LAMMPS(**kwargs)
        except ImportError:
            print("  - LAMMPS calculator not available. Install with: pip install lammps")
    elif potential_type == "emt":
        try:
            from ase.calculators.emt import EMT
            print("  - Using EMT calculator as fallback")
            return EMT()
        except ImportError:
            print("  - EMT calculator not available. Install with: pip install ase")
    else:
        print(f"  - Unsupported potential type: {potential_type}")
    
    sys.exit(1)         


def read_displaced_supercells(directory='.', pattern='POSCAR-*'):
    """
    读取位移超胞文件
    
    Parameters:
        directory (str): 文件所在目录
        pattern (str): 文件名格式
        
    Returns:
        list: 位移超胞结构列表
    """
    print(f"\nReading displaced supercells from {directory}...")
    
    files = glob.glob(os.path.join(directory, pattern))
    files = [f for f in files if os.path.isfile(f) and f.endswith(('.vasp', '.poscar', ''))]
    files.sort()
    
    if not files:
        print(f"  - No displaced supercell files found matching pattern: {pattern}")
        return []
    
    print(f"  - Found {len(files)} displaced supercell files")
    structures = []
    for i, f in enumerate(files):
        print(f"  - {i+1}: {os.path.basename(f)}")
        try:
            structure = read_vasp(f)
            structures.append(structure)
            print(f"  - Read structure from: {os.path.basename(f)} ({len(structure)} atoms)")
        except Exception as e:
            print(f"  - Error reading {f}: {e}")
    
    return structures


def calculate_forces_with_ml_potential(structures, ml_calculators):
    """
    机器学习势函数计算所有结构的力
    
    Parameters:
        structures (list): 位移超胞结构列表
        ml_calculators (ASE calculator): 机器学习势函数计算器
        
    Returns:
        list: 力列表
    """
    print(f"\nCalculating forces for {len(structures)} structures...")
    forces_list = []
    forces_calc_start_time = time.time()
    
    for i, structure in enumerate(structures):
        print(f"  - Calculating forces for structure {i+1}/{len(structures)}...")
        ase_atoms = Atoms(symbols=structure.symbols,
                         positions=structure.positions,
                         cell=structure.cell,
                         pbc=[True, True, True])
        ase_atoms.calc = ml_calculators  #set ase calculator
        forces = ase_atoms.get_forces()
        forces_list.append(forces)
        print(f"  - Forces calculated for {len(forces)} atoms")
        
    forces_calc_time = time.time() - forces_calc_start_time
    print(f"  - Total force calculation time: {forces_calc_time:.2f} seconds")
    print(f"  - Average time per structure: {forces_calc_time/len(structures):.2f} seconds")

    return forces_list


def generate_force_sets_from_supercells(original_supercell, displaced_supercells, forces_list):
    """
    从结构和力列表生成FORCE_SETS数据格式
    
    Parameters:
        original_supercell (PhonopyAtoms): 原始超胞结构
        displaced_supercells (list): 位移超胞结构列表
        force_list (list): 对应的力列表
        
    Returns:
        dict: FORCE_SETS格式的字典
    """
    print("\nGenerating FORCE_SETS format...")
    natom = len(original_supercell)
    
    force_sets = {'natom': natom,
                 'first_atoms': []}

    # 对于phonopy生成的位移构型，通常每个POSCAR-*对应一个原子的位移
    for i, (supercell, forces) in enumerate(zip(displaced_supercells, forces_list)):
        # 计算相对于原始超胞的位移
        disps = supercell.positions - original_supercell.positions
        
        # 找到最大位移的原子
        max_disp_idx = np.argmax(np.linalg.norm(disps, axis=1))
        max_disp = disps[max_disp_idx]
        
        force_sets['first_atoms'].append({'number': int(max_disp_idx),
                                         'displacement': max_disp.tolist(),
                                         'forces': forces.tolist()
                                         })
    
    print(f"  - FORCE_SETS format generated with {len(force_sets['first_atoms'])} displaced configurations")
          
    return force_sets


if __name__ == "__main__":
    try:
        import argparse
        parser = argparse.ArgumentParser(description='Calculate forces for displaced supercells generated by Phonopy using ML potentials and write FORCE_SETS file')
        parser.add_argument('--calculator', type=str, default='nep',
                          choices=['mace', 'dp', 'nep', 'flare', 'gap', 'lammps', 'emt'],
                          help='Type of machine learning calculator (defacult: nep)')
        parser.add_argument('--potential', type=str, default='nep.txt',
                           help='machine learning potential file (default: nep.txt)')
        parser.add_argument('--directory', type=str, default='.',
                           help='Directory containing displaced supercell files (default: current directory)')
        parser.add_argument('--pattern', type=str, default='POSCAR-*',
                           help='File pattern for displaced supercell files (default: POSCAR-*)')
        parser.add_argument('--original_supercell', type=str, default='SPOSCAR',
                           help='Original supercell file for reference (default: SPOSCAR)')
        parser.add_argument('--output', type=str, default='FORCE_SETS',
                           help='Output FORCE_SETS file (default: FORCE_SETS)')
        args = parser.parse_args()
    except (ImportError, SystemExit):
        args = type('Args', (), {
            'calculator': 'nep', 'potential': 'nep.txt',
            'directory': '.', 'pattern': 'POSCAR-*', 'original_supercell': 'SPOSCAR',
            'output': 'FORCE_SETS'
        })()
    
    print('\nChecking input files...')
    if args.calculator != 'emt' and not os.path.exists(args.potential):
        print(f"  - Error: Potential file not found: {args.potential}")
        sys.exit(1)
    if not os.path.exists(args.directory):
        print(f"  - Error: Directory not found: {args.directory}")
        sys.exit(1)
    original_supercell_file = os.path.join(args.directory, args.original_supercell)
    if not os.path.exists(original_supercell_file):
        print(f"  - Error: Original supercell file not found: {original_supercell_file}")
        sys.exit(1)
    
    # 读取结构
    original_supercell = read_vasp(original_supercell_file)
    displaced_supercells = read_displaced_supercells(args.directory, args.pattern)
    
    # 创建计算器并计算力
    ml_calculator = create_ml_calculator(potential_type=args.calculator, potential_file=args.potential)
    forces_list = calculate_forces_with_ml_potential(displaced_supercells, ml_calculator)
    
    # 写入FORCE_SETS文件
    force_sets = generate_force_sets_from_supercells(original_supercell, displaced_supercells, forces_list)
    print(f"\nWriting FORCE_SETS file: {args.output}...")
    write_FORCE_SETS(force_sets, filename=args.output)
    
    print("\nCalculation completed successfully")
    print("\nNext steps:")
    print(f"phonopy-load --band q-path --eigvecs -p -s")
